---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: "300"
organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUAloBuUOFD7PfJiHWJ9vVnh9J9ZAwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjEwMTA2MDkyMjAwWhcNMzYwMTAzMDkyMjAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDlT
          /UYqtY7vLG9ndCn7qZkURvZzmRcKFBBvpXyNMmBqDEFQBYMr5hSJtvFAAPsbSbSJ
          uZSIKWkwE/rSw9Cw5uKjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBSp/2hOIAgWql2jTQ5NEcPx7FXzrTAKBggqhkjOPQQD
          AgNHADBEAiAYfnMcighLiecBQ1Q5eE6MTMz+bZF4fBwZOPFaU53IIgIgOjoJc6Fr
          eH2i0h1/v3POP3rkpqF5xqW/+pHiKzjIWGA=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
  peer1.org1.example.com:
    url: grpcs://localhost:8051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUAloBuUOFD7PfJiHWJ9vVnh9J9ZAwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjEwMTA2MDkyMjAwWhcNMzYwMTAzMDkyMjAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDlT
          /UYqtY7vLG9ndCn7qZkURvZzmRcKFBBvpXyNMmBqDEFQBYMr5hSJtvFAAPsbSbSJ
          uZSIKWkwE/rSw9Cw5uKjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBSp/2hOIAgWql2jTQ5NEcPx7FXzrTAKBggqhkjOPQQD
          AgNHADBEAiAYfnMcighLiecBQ1Q5eE6MTMz+bZF4fBwZOPFaU53IIgIgOjoJc6Fr
          eH2i0h1/v3POP3rkpqF5xqW/+pHiKzjIWGA=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      hostnameOverride: peer1.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUAloBuUOFD7PfJiHWJ9vVnh9J9ZAwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjEwMTA2MDkyMjAwWhcNMzYwMTAzMDkyMjAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDlT
          /UYqtY7vLG9ndCn7qZkURvZzmRcKFBBvpXyNMmBqDEFQBYMr5hSJtvFAAPsbSbSJ
          uZSIKWkwE/rSw9Cw5uKjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBSp/2hOIAgWql2jTQ5NEcPx7FXzrTAKBggqhkjOPQQD
          AgNHADBEAiAYfnMcighLiecBQ1Q5eE6MTMz+bZF4fBwZOPFaU53IIgIgOjoJc6Fr
          eH2i0h1/v3POP3rkpqF5xqW/+pHiKzjIWGA=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
